FrogInsulationManufacturersInc2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainWepSite.urls', namespace='MainWepSite')),
    path('', include('orders.urls', namespace='orders')),
    path('', include('MainOffice.urls', namespace='MainOffice')),
    path('', include('Warehouse1.urls', namespace='Warehouse1')),
    path("select2/", include("django_select2.urls")),
    path('', include('custom_users.urls', namespace='custom_users')),
    # path('', include('PaymentsApp.urls')),
    path('', include('paypal.standard.ipn.urls')),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MainOffice/urls.py
from django.urls import path
from .views import (
    PresidentCreateView, OperationalManagerCreateView, AccountsReceivableManagerCreateView,
    AccountsReceivableCreateView, AccountsPayableCreateView,
    PresidentListView, OperationalManagerListView, AccountsReceivableManagerListView,
    AccountsReceivableListView, AccountsPayableListView,
    PresidentUpdateView, OperationalManagerUpdateView, AccountsReceivableManagerUpdateView,
    AccountsReceivableUpdateView, AccountsPayableUpdateView,
    PresidentDeleteView, OperationalManagerDeleteView, AccountsReceivableManagerDeleteView,
    AccountsReceivableDeleteView, AccountsPayableDeleteView,
    PresidentLoginView, OperationalManagerLoginView, AccountsReceivableManagerLoginView,
    AccountsReceivableLoginView, AccountsPayableLoginView,
    AllEmployeesListView, EmployeeRegistrationView, BaseLoginView,

)

app_name = 'MainOffice'

urlpatterns = [
    # CRUD views for President
    path('create/president/', PresidentCreateView.as_view(), name='create_president'),
    path('list/president/', PresidentListView.as_view(), name='list_president'),
    path('update/president/<int:pk>/', PresidentUpdateView.as_view(), name='update_president'),
    path('delete/president/<int:pk>/', PresidentDeleteView.as_view(), name='delete_president'),

    # CRUD views for OperationalManager
    path('create/operational_manager/', OperationalManagerCreateView.as_view(), name='create_operational_manager'),
    path('list/operational_manager/', OperationalManagerListView.as_view(), name='list_operational_manager'),
    path('update/operational_manager/<int:pk>/', OperationalManagerUpdateView.as_view(),
         name='update_operational_manager'),
    path('delete/operational_manager/<int:pk>/', OperationalManagerDeleteView.as_view(),
         name='delete_operational_manager'),

    # CRUD views for AccountsReceivableManager
    path('create/accounts_receivable_manager/', AccountsReceivableManagerCreateView.as_view(),
         name='create_accounts_receivable_manager'),
    path('list/accounts_receivable_manager/', AccountsReceivableManagerListView.as_view(),
         name='list_accounts_receivable_manager'),
    path('update/accounts_receivable_manager/<int:pk>/', AccountsReceivableManagerUpdateView.as_view(),
         name='update_accounts_receivable_manager'),
    path('delete/accounts_receivable_manager/<int:pk>/', AccountsReceivableManagerDeleteView.as_view(),
         name='delete_accounts_receivable_manager'),

    # CRUD views for AccountsReceivable
    path('create/accounts_receivable/', AccountsReceivableCreateView.as_view(), name='create_accounts_receivable'),
    path('list/accounts_receivable/', AccountsReceivableListView.as_view(), name='list_accounts_receivable'),
    path('update/accounts_receivable/<int:pk>/', AccountsReceivableUpdateView.as_view(),
         name='update_accounts_receivable'),
    path('delete/accounts_receivable/<int:pk>/', AccountsReceivableDeleteView.as_view(),
         name='delete_accounts_receivable'),

    # CRUD views for AccountsPayable
    path('create/accounts_payable/', AccountsPayableCreateView.as_view(), name='create_accounts_payable'),
    path('list/accounts_payable/', AccountsPayableListView.as_view(), name='list_accounts_payable'),
    path('update/accounts_payable/<int:pk>/', AccountsPayableUpdateView.as_view(), name='update_accounts_payable'),
    path('delete/accounts_payable/<int:pk>/', AccountsPayableDeleteView.as_view(), name='delete_accounts_payable'),

    # Login views
    path('login/president/', PresidentLoginView.as_view(), name='login_president'),
    path('login/operational_manager/', OperationalManagerLoginView.as_view(), name='login_operational_manager'),
    path('login/accounts_receivable_manager/', AccountsReceivableManagerLoginView.as_view(),
         name='login_accounts_receivable_manager'),
    path('login/accounts_receivable/', AccountsReceivableLoginView.as_view(), name='login_accounts_receivable'),
    path('login/accounts_payable/', AccountsPayableLoginView.as_view(), name='login_accounts_payable'),

    # Other views
    path('contact/', AllEmployeesListView.as_view(), name='all_employees_list'),
    path('register/', EmployeeRegistrationView.as_view(), name='register_employee'),
    path('login/', BaseLoginView.as_view(), name='login_employee'),

]

Warehouse1/urls.py
from django.urls import path
from .views import (
    WarehouseSupervisorCreateView, WarehouseSupervisorListView, WarehouseSupervisorUpdateView,
    WarehouseSupervisortDeleteView, WarehouseWorkerCreateView, WarehouseWorkerListView, WarehouseWorkerUpdateView,
    WarehouseWorkerDeleteView, DriverCreateView, DriverListView, DriverUpdateView, DriverDeleteView,
    WarehouseWorkerDriverCreateView, WarehouseWorkerDriverListView, WarehouseWorkerDriverUpdateView,
    WarehouseWorkerDriverDeleteView, WarehouseSupervisorLoginView, WarehouseWorkerLoginView, DriverLoginView,
    WarehouseWorkerDriverLoginView, AllEmployeesWarehouseListView, EmployeeWarehouseRegistrationView,
    BaseWarehouseLoginView
)

app_name = 'Warehouse1'

urlpatterns = [
    # CRUD views for WarehouseSupervisor
    path('create/warehouse_supervisor/', WarehouseSupervisorCreateView.as_view(), name='create_warehouse_supervisor'),
    path('list/warehouse_supervisor/', WarehouseSupervisorListView.as_view(), name='list_warehouse_supervisor'),
    path('update/warehouse_supervisor/<int:pk>/', WarehouseSupervisorUpdateView.as_view(), name='update_warehouse_supervisor'),
    path('delete/warehouse_supervisor/<int:pk>/', WarehouseSupervisortDeleteView.as_view(), name='delete_warehouse_supervisor'),

    # CRUD views for WarehouseWorker
    path('create/warehouse_worker/', WarehouseWorkerCreateView.as_view(), name='create_warehouse_worker'),
    path('list/warehouse_worker/', WarehouseWorkerListView.as_view(), name='list_warehouse_worker'),
    path('update/warehouse_worker/<int:pk>/', WarehouseWorkerUpdateView.as_view(), name='update_warehouse_worker'),
    path('delete/warehouse_worker/<int:pk>/', WarehouseWorkerDeleteView.as_view(), name='delete_warehouse_worker'),

    # CRUD views for Driver
    path('create/driver/', DriverCreateView.as_view(), name='create_driver'),
    path('list/driver/', DriverListView.as_view(), name='list_driver'),
    path('update/driver/<int:pk>/', DriverUpdateView.as_view(), name='update_driver'),
    path('delete/driver/<int:pk>/', DriverDeleteView.as_view(), name='delete_driver'),

    # CRUD views for WarehouseWorkerDriver
    path('create/warehouse_worker_driver/', WarehouseWorkerDriverCreateView.as_view(), name='create_warehouse_worker_driver'),
    path('list/warehouse_worker_driver/', WarehouseWorkerDriverListView.as_view(), name='list_warehouse_worker_driver'),
    path('update/warehouse_worker_driver/<int:pk>/', WarehouseWorkerDriverUpdateView.as_view(), name='update_warehouse_worker_driver'),
    path('delete/warehouse_worker_driver/<int:pk>/', WarehouseWorkerDriverDeleteView.as_view(), name='delete_warehouse_worker_driver'),

    # Login views
    path('login/warehouse_supervisor/', WarehouseSupervisorLoginView.as_view(), name='login_warehouse_supervisor'),
    path('login/warehouse_worker/', WarehouseWorkerLoginView.as_view(), name='login_warehouse_worker'),
    path('login/driver/', DriverLoginView.as_view(), name='login_driver'),
    path('login/warehouse_worker_driver/', WarehouseWorkerDriverLoginView.as_view(), name='login_warehouse_worker_driver'),

    # Other views
    path('all_employees_list/', AllEmployeesWarehouseListView.as_view(), name='all_employees_warehouse_list'),
    path('warehouse_register/', EmployeeWarehouseRegistrationView.as_view(), name='warehouse_register'),
    path('warehouse_login/', BaseWarehouseLoginView.as_view(), name='warehouse_login'),

]

orders/urls.py
from django.urls import path, register_converter

from . import views
from .views import CustomerOrderDetailView, OperatorOrderDetailView, BaseOrderListView, OperatorOrderListView, \
    CanceledOrderListView, DriverOrderDetailView, driver_order_list, mark_notification_as_read
from . import converters
from .views import ProductListView, ProductDetailViewBoxed, ProductDetailViewSingle

register_converter(converters.BoolConverter, 'bool')







app_name = 'orders'  # только если вы используете пространство имен

urlpatterns = [

    path('notifications/read/<int:notification_id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('save-order-details/', views.save_order_details, name='save_order_details'),

    # Путь к странице подтверждения заказа
    path('confirm-order/', views.confirm_order, name='confirm_order'),

    # Пути для обработки результатов платежа через PayPal
    path('payment-success/<uuid:transaction_id>/', views.payment_success, name='payment-success'),
    path('payment-failed/<uuid:transaction_id>/', views.payment_failed, name='payment-failed'),

    # Путь для обработки IPN от PayPal
    path('paypal-ipn/', views.paypal_ipn, name='paypal_ipn'),

    # Путь для подтверждения офлайн-заказа
    path('offline-order-confirm/', views.offline_order_confirm, name='offline_order_confirm'),

    # Путь для страницы деталей заказа (предполагается, что у вас есть такая страница)


    # URL для PayPal IPN
    # path('paypal-ipn/', views.paypal_ipn_listener, name='paypal-ipn'),


    # path('get_client_data/', views.get_client_data, name='get_client_data'),
    path('get-address-details/', views.get_address_details, name='get-address-details'),


    path('order/<int:order_id>/', CustomerOrderDetailView.as_view(), name='customer_order_detail'),
    path('operator/order/<int:order_id>/', OperatorOrderDetailView.as_view(), name='operator_order_detail'),

    path('edit_order_item/<int:order_id>/<str:source>/', views.edit_order_item, name='edit_order_item'),

    path('order_item/delete/<int:order_id>/', views.delete_order_item, name='delete_order_item'),




    path('edit_order_address/<int:order_id>/<str:source>/', views.edit_order_address, name='edit_order_address'),



    path('edit_order_call_add_product/<int:order_id>/<str:source>/', views.EditOrderCallView.as_view(), name='edit_order_call_add_product'),

    path('operator_create_order/', views.operator_create_order, name='operator_create_order'),

    path('order_list/', BaseOrderListView.as_view(), name='base_order_list'),
    path('operator_orders/', OperatorOrderListView.as_view(), name='operator_order_list'),
    path('take_order/<int:order_id>/', views.take_order, name='take_order'),
    path('own_orders/', views.own_operator_order_list, name='own_operator_order_list'),

    path('process_order/<int:order_id>/', views.process_order, name='process_order'),

    path('cancel_order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('canceled_orders/', CanceledOrderListView.as_view(), name='canceled_order_list'),
    path('order/<int:order_id>/return-to-processing/', views.return_order_to_processing_view, name='return_order_to_processing'),

    path('release_order/<int:order_id>/', views.release_order, name='release_order'),
    path('release_order_to_supervisor/<int:order_id>/', views.release_order_to_supervisor, name='release_order_to_supervisor'),

    path('warehouse_orders/', views.warehouse_order_list, name='warehouse_order_list'),
    path('warehouse_orders_d/<int:order_id>/', views.warehouse_order_detail, name='warehouse_order_detail'),
    path('pass_to_warehouse/<int:order_id>/', views.pass_order_to_warehouse, name='pass_order_to_warehouse'),
    path('supervisor_take_order/<int:order_id>/', views.supervisor_take_order_back, name='supervisor_take_order'),

    path('driver_orders/<int:driver_id>/', driver_order_list, name='driver_order'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),

    path('driver_orders/', views.own_driver_order_list, name='own_driver_order_list'),
    path('driver_order_detail/<int:order_id>/', DriverOrderDetailView, name='driver_order_detail'),
    path('pass_to_driver/<int:order_id>/', views.pass_order_to_driver, name='pass_order_to_driver'),
    path('driver_orders/<int:order_id>/mark_as_loaded/', views.mark_as_loaded_driver, name='mark_as_loaded'),
    path('supervisor_mark_as_loaded/<int:order_id>/<int:driver_id>/', views.mark_as_loaded_supervisor,
         name='mark_as_loaded_supervisor'),
    path('mark_truck_as_fully_loaded/', views.mark_truck_as_fully_loaded_driver, name='mark_truck_as_fully_loaded'),
    path('supervisor_mark_truck/<int:driver_id>/', views.mark_truck_as_fully_loaded_supervisor,
         name='mark_truck_as_fully_loaded_supervisor'),
    path('current_user/', views.current_user, name='current_user'),



    path('api/update_based_on_package_call/<str:package_type>/', views.update_based_on_package_call, name='update_based_on_package_call'),
    path('api/update_based_on_product_number_call/<str:package_type>/<str:product_number>/', views.update_based_on_product_number_call,
         name='update_based_on_product_number_call'),
    path('api/update_based_on_sku_call/<str:package_type>/<str:product_number>/<str:size_sku>/', views.update_based_on_sku_call,
         name='update_based_on_sku_call'),

    path('api/update_based_on_size_call/<str:package_type>/<str:product_number>/<str:size_sku>/<str:size_value>/', views.update_based_on_size_call, name='update_based_on_size_call'),



# path('products_order_call/<int:order_id>/add_product/', ProductListView.as_view(), name='product_list_order'),
#     path('product/<slug:slug>/boxed/<int:order_id>/', views.ProductDetailViewBoxed.as_view(),
#          name='product_detail_boxed'),
#     path('product/<slug:slug>/single/<int:order_id>/', views.ProductDetailViewSingle.as_view(), name='product_detail_single'),
#     path('add-product-to-order/<int:product_id>/<int:size_id>/<int:order_id>/', views.add_product_to_order, name='add_product_to_order'),


    path('products_order/<int:order_id>/', ProductListView.as_view(), name='product_list_order'),
    path('products_order/<slug:slug>/boxed/<int:order_id>/', ProductDetailViewBoxed.as_view(),
         name='product_detail_boxed'),

    path('products_order/<slug:slug>/single/<int:order_id>/', ProductDetailViewSingle.as_view(),
         name='product_detail_single'),

    path('add_product/<int:product_id>/<int:size_id>/<int:order_id>/', views.add_product_to_order,
         name='add_product_to_order'),

]

templates/templates_for_warehouse/all_employees_warehouse_list.html
{% extends "ForMainWepSite/base.html" %}

{% block content %}
<h1>All Employees</h1>

<h2>Warehouse Supervisor</h2>
<ul>
    {% for warehouse_supervisor in warehouse_supervisors %}
    <li>{{ warehouse_supervisor.user }}</li>
    {% empty %}
      <li>No employees found.</li>
    {% endfor %}
</ul>

<h2>Warehouse Worker</h2>
<ul>
    {% for warehouse_worker in warehouse_workers %}
    <li>{{ warehouse_worker.user }}</li>
    {% empty %}
      <li>No employees found.</li>
    {% endfor %}
</ul>

<h2>Driver</h2>
<ul>
    {% for driver in drivers %}
    <li>{{ driver.user }}</li>
    {% empty %}
      <li>No employees found.</li>
    {% endfor %}
</ul>

<h2>Warehouse Worker and Driver</h2>
<ul>
    {% for warehouse_worker_driver in warehouse_worker_drivers %}
    <li>{{ warehouse_worker_driver.user }}</li>
    {% empty %}
      <li>No employees found.</li>
    {% endfor %}
</ul>

{% endblock %}

templates/templates_for_warehouse/employee_warehouse_confirm_delete.html
{% extends "ForMainWepSite/base.html" %}

{% block content %}
  <h2>Confirm Delete</h2>
  <p>Are you sure you want to delete {{ object.user }}?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Yes, Delete</button>
    <a href="{% url 'MainOffice:list_president' %}">Cancel</a>
  </form>
{% endblock %}

templates/templates_for_warehouse/employee_warehouse_create_update_form.html
{% extends "ForMainWepSite/base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h2>Детализированная информация</h2>
    {{ form.as_p }}
    <input type="submit" value="Сохранить">
</form>



{#  <h2>{% if form.instance.pk %}Update{% else %}Create{% endif %} Employee</h2>#}
{#  <form method="post">#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}#}
{#    <button type="submit">Save</button>#}
{#  </form>#}
{% endblock %}

templates/templates_for_warehouse/employee_warehouse_list.html
{% extends "ForMainWepSite/base.html" %}

{% block content %}
  <h2>List of Employees</h2>
  <ul>
    {% for employee in object_list %}
      <li>{{ employee.user }}</li>
    {% empty %}
      <li>No employees found.</li>
    {% endfor %}
  </ul>
{% endblock %}

templates/templates_for_warehouse/own_driver_order_list.html
{% extends "ForMainWepSite/base.html" %}



{% block content %}




<h1>Own Orders</h1>
    {% if request.user.driver%}
    <a href="{% url 'orders:own_driver_order_list'%}" class="btn btn-success">My list</a>
    <a href="{% url 'orders:warehouse_order_list'%}" class="btn btn-primary">warehouse list</a>
    {% endif %}


{% if request.user.president or request.user.operationalmanager or request.user.accountsreceivablemanager or request.user.accountsreceivable or request.user.accountspayable %}    <a href="{% url 'orders:canceled_order_list'%}" class="btn btn-primary">canceled list</a>
    <a href="{% url 'orders:own_operator_order_list'%}" class="btn btn-success">My Own list</a>
    <a href="{% url 'orders:operator_order_list'%}" class="btn btn-primary">new order list</a>
    <a href="{% url 'orders:warehouse_order_list'%}" class="btn btn-primary">warehouse list</a>
    <a href="/warehouse_orders/#drivers-list" class="btn btn-primary">driver order list</a>
    <a href="{% url 'orders:operator_create_order'%}" class="btn btn-info">create new order</a>

    {% endif %}

    <br>
    <br>

<table>

    <tbody>

 {% for order in orders %}
<div>
    <h2>Order #{{ order.id }}</h2>
    <p>Status: {{ order.get_status_display }}</p>
    {% if request.user.driver%}
    <a href="{% url 'orders:release_order_to_supervisor' order.id %}" class="btn-danger">back to supervisor list</a>
    {% endif %}

    <a href="{% url 'orders:driver_order_detail' order.id %}" class="btn-success">View order details</a>
{% if request.user.president or request.user.operationalmanager or request.user.accountsreceivablemanager or request.user.accountsreceivable or request.user.accountspayable %}
    <a href="{% url 'orders:take_order' order.id %}" class="btn-danger">Take order</a>
    {% endif %}


    {% if request.user.driver%}
<div class="order-container">
    <form method="post" action="{% url 'orders:mark_as_loaded' order.id %}">
        {% csrf_token %}
        <input type="checkbox" id="loaded-{{ order.id }}" name="is_loaded" {% if order.is_loaded %}checked{% endif %} onchange="this.form.submit()">
        <label for="loaded-{{ order.id }}"></label>
    </form>
    {% if order.is_loaded %}
    <div class="loaded-time">Loaded{{ order.loaded_at }}</div>
    {% endif %}
    {% endif %}

</div>
</div>
<br>
{% endfor %}
     {% if request.user.driver%}
    <a href="{% url 'orders:mark_truck_as_fully_loaded' %}">Пометить грузовик как полностью загруженный</a>
    {% endif %}


    </tbody>
</table>
    {% for notification in notifications %}
    <div class="alert alert-info">
        {{ notification.message }}
    </div>
{% endfor %}


    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% endblock %}

templates/templates_for_warehouse/warehouse_login.html
{% extends "ForMainWepSite/base.html" %}

{% block content %}
<div class="login-container">
    <h2>Вход в систему</h2>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="submit-button">
            <button type="submit">Войти</button>
        </div>
    </form>
    
    <div class="register-link">
{#        <p>Еще не зарегистрированы? <a href="{% url 'MainOffice:register.html' %}">Зарегистрироваться</a></p>#}
    </div>
</div>
{% endblock %}

{% block additional_css %}
<style>
    .login-container {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .submit-button {
        margin-top: 10px;
    }

    .register-link {
        margin-top: 15px;
        text-align: center;
    }
</style>
{% endblock %}