FrogInsulationManufacturersInc2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainWepSite.urls', namespace='MainWepSite')),
    path('', include('orders.urls', namespace='orders')),
    path('', include('MainOffice.urls', namespace='MainOffice')),
    path('', include('Warehouse1.urls', namespace='Warehouse1')),
    path("select2/", include("django_select2.urls")),
    path('', include('custom_users.urls', namespace='custom_users')),
    # path('', include('PaymentsApp.urls')),
    path('', include('paypal.standard.ipn.urls')),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MainWepSite/urls.py
from django.urls import path
from . import views
from MainWepSite.views import BlogPostListView, blog_post_detail, BlogPostCreateView, BlogPostUpdateView, \
    BlogPostDeleteView, CommentListView, CommentDeleteView

app_name = 'MainWepSite'  # только если вы используете пространство имен
# handler404 = 'FrogInsulationManufacturersInc2.views.error_404_view'

urlpatterns = [
    path('', views.index, name='index'),  # Эта строка указывает, что корневой URL будет обрабатываться функцией index
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),

    # path('api/get_product_by_sku/<str:sku>/', views.get_product_by_sku, name='get_product_by_sku'),
    path('error/', views.error_404_view, name='error_page'),

    path('update_based_on_package/<int:product_id>/<str:package_type>/', views.update_based_on_package, name='update_based_on_package'),
    path('update_based_on_product_number/<int:product_id>/<zeston>/<str:package_type>/', views.update_based_on_product_number, name='update_based_on_product_number'),
    path('update_based_on_sku/<int:product_id>/<str:size_sku>/', views.update_based_on_sku, name='update_based_on_sku'),
    path('update_based_on_size_and_package/<int:product_id>/<size_desc>/<str:package_type>/', views.update_based_on_size_and_package, name='update_based_on_size_and_package'),

    path('category/<slug:slug>/', views.category_detail, name='category_detail'),
    path('brand/<slug:slug>/', views.brand_detail, name='brand_detail'),

    path('cart/', views.view_cart, name='view_cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/(?P<sku>[\w-]+)/\\Z', views.remove_from_cart, name='remove_from_cart'),
    path('update_cart_quantity/(?P<sku>[\w-]+)/\\Z', views.update_cart_quantity, name='update_cart_quantity'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),

    path('recent-views/', views.recent_views, name='recent-views'),  # URL для недавно просмотренных продуктов

    path('blog/', BlogPostListView.as_view(), name='post_list'),
    path('blog/category/<slug:category_slug>/', BlogPostListView.as_view(), name='post_list_by_category'),
    path('blog/<slug:slug>/', blog_post_detail, name='blog_detail'),
    path('blog_new/', BlogPostCreateView.as_view(), name='blog_new'),
    path('blog/<int:pk>/edit/', BlogPostUpdateView.as_view(), name='blog_edit'),
    path('blog/<int:pk>/delete/', BlogPostDeleteView.as_view(), name='blog_delete'),

    path('blog_comments/<slug:slug>/', CommentListView.as_view(), name='comment_list'),
    path('comment/delete/<int:pk>/', CommentDeleteView.as_view(), name='comment_delete'),



]

custom_users/urls.py
from django.urls import path
from custom_users import views
from custom_users.views import ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView

app_name = 'custom_users'  # только если вы используете пространство имен

urlpatterns = [

    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/add/', ClientCreateView.as_view(), name='client_add'),
    path('clients/<int:pk>/edit/', ClientUpdateView.as_view(), name='client_edit'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),

    path('register_clients/', views.register, name='register_clients'),





    path('dashboard_customer/', views.dashboard_customer, name='dashboard_customer'),
    path('profile/update/', views.update_profile, name='update_profile'),
    path('address/add/', views.add_address, name='add_address'),
    path('address/edit/<int:address_id>/', views.edit_address, name='edit_address'),

]

orders/urls.py
from django.urls import path, register_converter

from . import views
from .views import CustomerOrderDetailView, OperatorOrderDetailView, BaseOrderListView, OperatorOrderListView, \
    CanceledOrderListView, DriverOrderDetailView, driver_order_list, mark_notification_as_read
from . import converters
from .views import ProductListView, ProductDetailViewBoxed, ProductDetailViewSingle

register_converter(converters.BoolConverter, 'bool')







app_name = 'orders'  # только если вы используете пространство имен

urlpatterns = [

    path('notifications/read/<int:notification_id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('save-order-details/', views.save_order_details, name='save_order_details'),

    # Путь к странице подтверждения заказа
    path('confirm-order/', views.confirm_order, name='confirm_order'),

    # Пути для обработки результатов платежа через PayPal
    path('payment-success/<uuid:transaction_id>/', views.payment_success, name='payment-success'),
    path('payment-failed/<uuid:transaction_id>/', views.payment_failed, name='payment-failed'),

    # Путь для обработки IPN от PayPal
    path('paypal-ipn/', views.paypal_ipn, name='paypal_ipn'),

    # Путь для подтверждения офлайн-заказа
    path('offline-order-confirm/', views.offline_order_confirm, name='offline_order_confirm'),

    # Путь для страницы деталей заказа (предполагается, что у вас есть такая страница)


    # URL для PayPal IPN
    # path('paypal-ipn/', views.paypal_ipn_listener, name='paypal-ipn'),


    # path('get_client_data/', views.get_client_data, name='get_client_data'),
    path('get-address-details/', views.get_address_details, name='get-address-details'),


    path('order/<int:order_id>/', CustomerOrderDetailView.as_view(), name='customer_order_detail'),
    path('operator/order/<int:order_id>/', OperatorOrderDetailView.as_view(), name='operator_order_detail'),

    path('edit_order_item/<int:order_id>/<str:source>/', views.edit_order_item, name='edit_order_item'),

    path('order_item/delete/<int:order_id>/', views.delete_order_item, name='delete_order_item'),




    path('edit_order_address/<int:order_id>/<str:source>/', views.edit_order_address, name='edit_order_address'),



    path('edit_order_call_add_product/<int:order_id>/<str:source>/', views.EditOrderCallView.as_view(), name='edit_order_call_add_product'),

    path('operator_create_order/', views.operator_create_order, name='operator_create_order'),

    path('order_list/', BaseOrderListView.as_view(), name='base_order_list'),
    path('operator_orders/', OperatorOrderListView.as_view(), name='operator_order_list'),
    path('take_order/<int:order_id>/', views.take_order, name='take_order'),
    path('own_orders/', views.own_operator_order_list, name='own_operator_order_list'),

    path('process_order/<int:order_id>/', views.process_order, name='process_order'),

    path('cancel_order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('canceled_orders/', CanceledOrderListView.as_view(), name='canceled_order_list'),
    path('order/<int:order_id>/return-to-processing/', views.return_order_to_processing_view, name='return_order_to_processing'),

    path('release_order/<int:order_id>/', views.release_order, name='release_order'),
    path('release_order_to_supervisor/<int:order_id>/', views.release_order_to_supervisor, name='release_order_to_supervisor'),

    path('warehouse_orders/', views.warehouse_order_list, name='warehouse_order_list'),
    path('warehouse_orders_d/<int:order_id>/', views.warehouse_order_detail, name='warehouse_order_detail'),
    path('pass_to_warehouse/<int:order_id>/', views.pass_order_to_warehouse, name='pass_order_to_warehouse'),
    path('supervisor_take_order/<int:order_id>/', views.supervisor_take_order_back, name='supervisor_take_order'),

    path('driver_orders/<int:driver_id>/', driver_order_list, name='driver_order'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),

    path('driver_orders/', views.own_driver_order_list, name='own_driver_order_list'),
    path('driver_order_detail/<int:order_id>/', DriverOrderDetailView, name='driver_order_detail'),
    path('pass_to_driver/<int:order_id>/', views.pass_order_to_driver, name='pass_order_to_driver'),
    path('driver_orders/<int:order_id>/mark_as_loaded/', views.mark_as_loaded_driver, name='mark_as_loaded'),
    path('supervisor_mark_as_loaded/<int:order_id>/<int:driver_id>/', views.mark_as_loaded_supervisor,
         name='mark_as_loaded_supervisor'),
    path('mark_truck_as_fully_loaded/', views.mark_truck_as_fully_loaded_driver, name='mark_truck_as_fully_loaded'),
    path('supervisor_mark_truck/<int:driver_id>/', views.mark_truck_as_fully_loaded_supervisor,
         name='mark_truck_as_fully_loaded_supervisor'),
    path('current_user/', views.current_user, name='current_user'),



    path('api/update_based_on_package_call/<str:package_type>/', views.update_based_on_package_call, name='update_based_on_package_call'),
    path('api/update_based_on_product_number_call/<str:package_type>/<str:product_number>/', views.update_based_on_product_number_call,
         name='update_based_on_product_number_call'),
    path('api/update_based_on_sku_call/<str:package_type>/<str:product_number>/<str:size_sku>/', views.update_based_on_sku_call,
         name='update_based_on_sku_call'),

    path('api/update_based_on_size_call/<str:package_type>/<str:product_number>/<str:size_sku>/<str:size_value>/', views.update_based_on_size_call, name='update_based_on_size_call'),



# path('products_order_call/<int:order_id>/add_product/', ProductListView.as_view(), name='product_list_order'),
#     path('product/<slug:slug>/boxed/<int:order_id>/', views.ProductDetailViewBoxed.as_view(),
#          name='product_detail_boxed'),
#     path('product/<slug:slug>/single/<int:order_id>/', views.ProductDetailViewSingle.as_view(), name='product_detail_single'),
#     path('add-product-to-order/<int:product_id>/<int:size_id>/<int:order_id>/', views.add_product_to_order, name='add_product_to_order'),


    path('products_order/<int:order_id>/', ProductListView.as_view(), name='product_list_order'),
    path('products_order/<slug:slug>/boxed/<int:order_id>/', ProductDetailViewBoxed.as_view(),
         name='product_detail_boxed'),

    path('products_order/<slug:slug>/single/<int:order_id>/', ProductDetailViewSingle.as_view(),
         name='product_detail_single'),

    path('add_product/<int:product_id>/<int:size_id>/<int:order_id>/', views.add_product_to_order,
         name='add_product_to_order'),

]

MainOffice/models.py
from django.contrib.auth.models import User
from django.db import models

MALE = 1
FEMALE = 2
OTHER = 3
GENDER_TYPE = (
    (MALE, 'MALE'),
    (FEMALE, 'FEMALE'),
    (OTHER, 'OTHER')
)

class MainOfficeEmployee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(null=True)
    phone_number = models.CharField(max_length=15, null=True)
    age = models.PositiveIntegerField(null=True)
    gender = models.PositiveSmallIntegerField(choices=GENDER_TYPE, null=True)

    class Meta:
        abstract = True

    def can_manage(self, other_employee):
        # Если текущий сотрудник президент, он может управлять всеми
        if isinstance(self, President):
            return True

        # Если текущий сотрудник операционный менеджер, он может управлять всеми, кроме президента
        elif isinstance(self, OperationalManager) and not isinstance(other_employee, President):
            return True

        # Операционный менеджер может управлять менеджерами по сбору средств
        elif isinstance(self, OperationalManager) and isinstance(other_employee, AccountsReceivableManager):
            return True

        # Менеджер по сбору средств может управлять сотрудниками по сбору средств и сотрудниками по оплате счетов
        elif isinstance(self, AccountsReceivableManager) and (
                isinstance(other_employee, AccountsReceivable) or isinstance(other_employee, AccountsPayable)):
            return True

        # Для всех других ситуаций возвращаем False
        return False


class President(MainOfficeEmployee):
    # Дополнительные поля и методы для президента
    pass


class OperationalManager(MainOfficeEmployee):
    # Дополнительные поля и методы для операционного менеджера
    pass


class AccountsReceivableManager(MainOfficeEmployee):
    # Дополнительные поля и методы для менеджера по сбору средств
    pass


class AccountsReceivable(MainOfficeEmployee):
    # Дополнительные поля и методы для сотрудника по сбору средств
    pass


class AccountsPayable(MainOfficeEmployee):
    # Дополнительные поля и методы для сотрудника по оплате счетов
    pass

templates/ForMainWepSite/brand_detail.html
{% extends "ForMainWepSite/base.html" %}
<!-- Расширяем базовый шаблон "base.html". -->

{% block title %}{{ brand.name }}{% endblock %}
<!-- Переопределяем блок "title", устанавливая заголовок страницы как имя бренда. -->

{% block content %}
<!-- Открываем блок "content" для размещения контента страницы. -->
    <h1>{{ brand.name }}</h1>
    <!-- Выводим название бренда как заголовок h1. -->

    <ul>
        <!-- Начинаем маркированный список. -->
        {% for product in products %}
        <!-- Начинаем цикл по товарам. -->
        <li><a href="{% url 'MainWepSite:brand_detail' product.slug %}">{{ product.name }}</a></li>
        <!-- Выводим список товаров с гиперссылками на их детали, используя URL-адрес "brand_detail". -->
        {% endfor %}
        <!-- Завершаем цикл. -->
    </ul>
    <!-- Завершаем маркированный список. -->



{% endblock %}
<!-- Завершаем блок "content". -->

templates/ForMainWepSite/category_detail.html
{% extends "ForMainWepSite/base.html" %}
<!-- Расширяем базовый шаблон "base.html". -->

{% block title %}{{ category.name }}{% endblock %}
<!-- Переопределяем блок "title", устанавливая заголовок страницы как имя категории. -->

{% block content %}
<!-- Открываем блок "content" для размещения контента страницы. -->
    <h1>{{ category.name }}</h1>
    <!-- Выводим название категории как заголовок h1. -->

    <ul>
        <!-- Начинаем маркированный список. -->
        {% for product in products %}
        <!-- Начинаем цикл по товарам. -->
        <li><a href="{% url 'MainWepSite:category_detail' product.slug %}">{{ product.name }}</a></li>
        <!-- Выводим список товаров с гиперссылками на их детали, используя URL-адрес "category_detail". -->
        {% endfor %}
        <!-- Завершаем цикл. -->
    </ul>
    <!-- Завершаем маркированный список. -->




{% endblock %}
<!-- Завершаем блок "content". -->

templates/ForMainWepSite/client_list.html
{% extends "ForMainWepSite/base.html" %}
<!-- Расширяем базовый шаблон "base.html". -->

{% block content %}
<!-- Открываем блок "content" для размещения контента страницы. -->
<h1>Clients List</h1>
<!-- Выводим заголовок "Clients List". -->
<table>
    <thead>
        <tr>
            <th> Name </th>
            <th> Email </th>
            <th>Phone</th>
            <th>Age</th>
            <th>Gender</th>
            <!-- и так далее для других полей -->
        </tr>
    </thead>
    <tbody>
        {% for client in clients %}
        <!-- Итерируемся по списку клиентов и выводим информацию о каждом клиенте. -->
        <tr>
            <!-- Создаем строку таблицы для каждого клиента. -->
            <td>{{ client.username }}</td>
            <!-- Отображаем имя клиента. -->
            <td>{{ client.email }}</td>
            <!-- Отображаем email клиента. -->
            <td>{{ client.phone_number }}</td>
            <!-- Отображаем номер телефона клиента. -->
            <td>{{ client.age }}</td>
            <!-- Отображаем возраст клиента. -->
            <td>{{ client.get_gender_display }}</td>
            <!-- Отображаем пол клиента с использованием метода get_gender_display(). -->
            <td><a href="{% url 'custom_users:client_edit' client.pk %}">Edit</a></td>
            <!-- Создаем ссылку "Edit" для редактирования клиента. -->
            <td><a href="{% url 'custom_users:client_delete' client.pk %}">Delete</a></td>
            <!-- Создаем ссылку "Delete" для удаления клиента. -->
            <!-- и так далее для других полей -->
        </tr>
        {% endfor %}
        <!-- Завершаем цикл for. -->
    </tbody>
</table>
<!-- Создаем таблицу для отображения данных о клиентах. -->

<a href="{% url 'custom_users:client_add' %}">Add New Client</a>
<!-- Создаем ссылку "Add New Client" для добавления нового клиента. -->
<a href="{% url 'MainWepSite:index' %}">Home</a>
<!-- Создаем ссылку "Home" для перехода на домашнюю страницу. -->


{% endblock %}
<!-- Завершаем блок "content". -->

templates/ForMainWepSite/error_page.html
{% extends "ForMainWepSite/base.html" %}


{% block content %}
    {% load static %}


	<title>Frog Portal NextJs Template</title>
	<meta charset="UTF-8">
	<meta content="IE=edge" http-equiv="X-UA-Compatible">
	<meta content="width=device-width, initial-scale=1.0" name="viewport">
	<meta content="Generated by create next app" name="description">
	<link href="{% static 'assets/images/froglogo1.svg' %}" rel="icon" sizes="20x20" type="image/gif">
	<meta content="6" name="next-head-count">
	<link href="{% static '/_next/static/css/f43a669c53b6c8f4.css' %}" rel="preload">
	<link data-n-g="" href="{% static '/_next/static/css/f43a669c53b6c8f4.css' %}" rel="stylesheet"><noscript data-n-css=""></noscript>
	<script defer src="{% static '/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js' %}">
	</script>
	<script defer src="{% static '/_next/static/chunks/webpack-c283a3d83359cc25.js' %}">
	</script>
	<script defer src="{% static '/_next/static/chunks/framework-3671d8951bf44e4e.js' %}">
	</script>
	<script defer src="{% static '/_next/static/chunks/main-0905829f35fb5e86.js' %}">
	</script>
	<script defer src="{% static '/_next/static/chunks/3424-510b4663ba497049.js' %}">
	</script>
	<script defer src="{% static '/_next/static/chunks/8004-e80da1eaf59a0e0a.js' %}">
	</script>
	<script defer src="{% static '/_next/static/chunks/7052-5ae32b0979dda73e.js' %}">
	</script>
	<script defer src="{% static '/_next/static/Eiwaci7in8GR_e4MnKVBk/_buildManifest.js' %}">
	</script>
	<script defer src="{% static '/_next/static/Eiwaci7in8GR_e4MnKVBk/_ssgManifest.js' %}">
	</script>
	<link href="{% static '/_next/static/chunks/717-a88701aea31ab923.js' %}" rel="prefetch">
	<link href="{% static '/_next/static/chunks/2008-4f1f586b51905cd8.js' %}" rel="prefetch">
	<link href="{% static '/_next/static/chunks/4875-abff460424e3af31.js' %}" rel="prefetch">
	<link href="{% static '/_next/static/chunks/689-4f6724f50310080b.js' %}" rel="prefetch">
	<link href="{% static '/_next/static/chunks/8863-fb3955eb4b42b806.js' %}" rel="prefetch">
	<link href="{% static '/_next/static/chunks/8960-8ab2b793893d1b59.js' %}" rel="prefetch">
	<link href="{% static '/_next/static/chunks/512-807b1b9847f0c759.js' %}" rel="prefetch">
	<link href="{% static '/_next/static/chunks/4532-630634613f9fb88b.js' %}" rel="prefetch">
	<link href="{% static '/_next/static/chunks/8931-3faabf1b275e128b.js' %}" rel="prefetch">



<div class="error-page-container">
        <img src="{% static 'detail/media/Error_1.png' %}" alt="Error Page Illustration" />
        <h1>Oops! Page not found.</h1>
        <p>We can't seem to find the page you're looking for. It might have been removed, had its name changed, or is temporarily unavailable.</p>
        <a href="/">Go Back Home</a>
    </div>



{% endblock %}

templates/ForMainWepSite/recent_views.html
{% extends "ForMainWepSite/base.html" %} <!-- Расширение базового шаблона -->

{% block content %} <!-- Определение блока контента страницы -->
{% load static %}

<div class="recent-views">
    <div class="title">
        <h5>Recent Gallery Views</h5>
    </div>
    {% if recent_views %}
        <div class="products">
            {% for product in recent_views %}
                <div class="product">
                    <a href="{{ product.detail_url }}">
                        {% if product.main_image %}
                            <img src="{{ product.main_image }}" alt="{{ product.name }}">
                        {% else %}
                            <img src="{% static 'assets/images/placeholder-image.png' %}" alt="Default Image">
                        {% endif %}
                        <p>{{ product.name }}</p>
                    </a>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>Вы еще не просмотрели ни одного товара.</p>
    {% endif %}
</div>

{% endblock %} <!-- Завершение блока контента страницы -->

templates/ForMainWepSite/wishlist.html
{% for product in products %}
<div class="product">
    <img src="{{ product.image.url }}" alt="{{ product.name }}" width="200">
    <div class="likes">
        <span>{{ product.likes }}</span>
        <a href="{% url 'MainWepSite:like_product' product.id %}" class="like-button">❤</a>
    </div>
    <a href="{% url 'MainWepSite:remove_from_wishlist' product.id %}">Удалить из списка желаний</a>
    <a href="{% url 'MainWepSite:add_to_cart' product.id %}" class="add-to-cart">Добавить в корзину</a>
    <a href="{% url 'MainWepSite:remove_from_cart' product.id %}" class="remove-from-cart">Удалить из корзины</a>

</div>


{% endfor %}