FrogInsulationManufacturersInc2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainWepSite.urls', namespace='MainWepSite')),
    path('', include('orders.urls', namespace='orders')),
    path('', include('MainOffice.urls', namespace='MainOffice')),
    path('', include('Warehouse1.urls', namespace='Warehouse1')),
    path("select2/", include("django_select2.urls")),
    path('', include('custom_users.urls', namespace='custom_users')),
    # path('', include('PaymentsApp.urls')),
    path('', include('paypal.standard.ipn.urls')),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MainOffice/urls.py
from django.urls import path
from .views import (
    PresidentCreateView, OperationalManagerCreateView, AccountsReceivableManagerCreateView,
    AccountsReceivableCreateView, AccountsPayableCreateView,
    PresidentListView, OperationalManagerListView, AccountsReceivableManagerListView,
    AccountsReceivableListView, AccountsPayableListView,
    PresidentUpdateView, OperationalManagerUpdateView, AccountsReceivableManagerUpdateView,
    AccountsReceivableUpdateView, AccountsPayableUpdateView,
    PresidentDeleteView, OperationalManagerDeleteView, AccountsReceivableManagerDeleteView,
    AccountsReceivableDeleteView, AccountsPayableDeleteView,
    PresidentLoginView, OperationalManagerLoginView, AccountsReceivableManagerLoginView,
    AccountsReceivableLoginView, AccountsPayableLoginView,
    AllEmployeesListView, EmployeeRegistrationView, BaseLoginView,

)

app_name = 'MainOffice'

urlpatterns = [
    # CRUD views for President
    path('create/president/', PresidentCreateView.as_view(), name='create_president'),
    path('list/president/', PresidentListView.as_view(), name='list_president'),
    path('update/president/<int:pk>/', PresidentUpdateView.as_view(), name='update_president'),
    path('delete/president/<int:pk>/', PresidentDeleteView.as_view(), name='delete_president'),

    # CRUD views for OperationalManager
    path('create/operational_manager/', OperationalManagerCreateView.as_view(), name='create_operational_manager'),
    path('list/operational_manager/', OperationalManagerListView.as_view(), name='list_operational_manager'),
    path('update/operational_manager/<int:pk>/', OperationalManagerUpdateView.as_view(),
         name='update_operational_manager'),
    path('delete/operational_manager/<int:pk>/', OperationalManagerDeleteView.as_view(),
         name='delete_operational_manager'),

    # CRUD views for AccountsReceivableManager
    path('create/accounts_receivable_manager/', AccountsReceivableManagerCreateView.as_view(),
         name='create_accounts_receivable_manager'),
    path('list/accounts_receivable_manager/', AccountsReceivableManagerListView.as_view(),
         name='list_accounts_receivable_manager'),
    path('update/accounts_receivable_manager/<int:pk>/', AccountsReceivableManagerUpdateView.as_view(),
         name='update_accounts_receivable_manager'),
    path('delete/accounts_receivable_manager/<int:pk>/', AccountsReceivableManagerDeleteView.as_view(),
         name='delete_accounts_receivable_manager'),

    # CRUD views for AccountsReceivable
    path('create/accounts_receivable/', AccountsReceivableCreateView.as_view(), name='create_accounts_receivable'),
    path('list/accounts_receivable/', AccountsReceivableListView.as_view(), name='list_accounts_receivable'),
    path('update/accounts_receivable/<int:pk>/', AccountsReceivableUpdateView.as_view(),
         name='update_accounts_receivable'),
    path('delete/accounts_receivable/<int:pk>/', AccountsReceivableDeleteView.as_view(),
         name='delete_accounts_receivable'),

    # CRUD views for AccountsPayable
    path('create/accounts_payable/', AccountsPayableCreateView.as_view(), name='create_accounts_payable'),
    path('list/accounts_payable/', AccountsPayableListView.as_view(), name='list_accounts_payable'),
    path('update/accounts_payable/<int:pk>/', AccountsPayableUpdateView.as_view(), name='update_accounts_payable'),
    path('delete/accounts_payable/<int:pk>/', AccountsPayableDeleteView.as_view(), name='delete_accounts_payable'),

    # Login views
    path('login/president/', PresidentLoginView.as_view(), name='login_president'),
    path('login/operational_manager/', OperationalManagerLoginView.as_view(), name='login_operational_manager'),
    path('login/accounts_receivable_manager/', AccountsReceivableManagerLoginView.as_view(),
         name='login_accounts_receivable_manager'),
    path('login/accounts_receivable/', AccountsReceivableLoginView.as_view(), name='login_accounts_receivable'),
    path('login/accounts_payable/', AccountsPayableLoginView.as_view(), name='login_accounts_payable'),

    # Other views
    path('contact/', AllEmployeesListView.as_view(), name='all_employees_list'),
    path('register/', EmployeeRegistrationView.as_view(), name='register_employee'),
    path('login/', BaseLoginView.as_view(), name='login_employee'),

]

Warehouse1/urls.py
from django.urls import path
from .views import (
    WarehouseSupervisorCreateView, WarehouseSupervisorListView, WarehouseSupervisorUpdateView,
    WarehouseSupervisortDeleteView, WarehouseWorkerCreateView, WarehouseWorkerListView, WarehouseWorkerUpdateView,
    WarehouseWorkerDeleteView, DriverCreateView, DriverListView, DriverUpdateView, DriverDeleteView,
    WarehouseWorkerDriverCreateView, WarehouseWorkerDriverListView, WarehouseWorkerDriverUpdateView,
    WarehouseWorkerDriverDeleteView, WarehouseSupervisorLoginView, WarehouseWorkerLoginView, DriverLoginView,
    WarehouseWorkerDriverLoginView, AllEmployeesWarehouseListView, EmployeeWarehouseRegistrationView,
    BaseWarehouseLoginView
)

app_name = 'Warehouse1'

urlpatterns = [
    # CRUD views for WarehouseSupervisor
    path('create/warehouse_supervisor/', WarehouseSupervisorCreateView.as_view(), name='create_warehouse_supervisor'),
    path('list/warehouse_supervisor/', WarehouseSupervisorListView.as_view(), name='list_warehouse_supervisor'),
    path('update/warehouse_supervisor/<int:pk>/', WarehouseSupervisorUpdateView.as_view(), name='update_warehouse_supervisor'),
    path('delete/warehouse_supervisor/<int:pk>/', WarehouseSupervisortDeleteView.as_view(), name='delete_warehouse_supervisor'),

    # CRUD views for WarehouseWorker
    path('create/warehouse_worker/', WarehouseWorkerCreateView.as_view(), name='create_warehouse_worker'),
    path('list/warehouse_worker/', WarehouseWorkerListView.as_view(), name='list_warehouse_worker'),
    path('update/warehouse_worker/<int:pk>/', WarehouseWorkerUpdateView.as_view(), name='update_warehouse_worker'),
    path('delete/warehouse_worker/<int:pk>/', WarehouseWorkerDeleteView.as_view(), name='delete_warehouse_worker'),

    # CRUD views for Driver
    path('create/driver/', DriverCreateView.as_view(), name='create_driver'),
    path('list/driver/', DriverListView.as_view(), name='list_driver'),
    path('update/driver/<int:pk>/', DriverUpdateView.as_view(), name='update_driver'),
    path('delete/driver/<int:pk>/', DriverDeleteView.as_view(), name='delete_driver'),

    # CRUD views for WarehouseWorkerDriver
    path('create/warehouse_worker_driver/', WarehouseWorkerDriverCreateView.as_view(), name='create_warehouse_worker_driver'),
    path('list/warehouse_worker_driver/', WarehouseWorkerDriverListView.as_view(), name='list_warehouse_worker_driver'),
    path('update/warehouse_worker_driver/<int:pk>/', WarehouseWorkerDriverUpdateView.as_view(), name='update_warehouse_worker_driver'),
    path('delete/warehouse_worker_driver/<int:pk>/', WarehouseWorkerDriverDeleteView.as_view(), name='delete_warehouse_worker_driver'),

    # Login views
    path('login/warehouse_supervisor/', WarehouseSupervisorLoginView.as_view(), name='login_warehouse_supervisor'),
    path('login/warehouse_worker/', WarehouseWorkerLoginView.as_view(), name='login_warehouse_worker'),
    path('login/driver/', DriverLoginView.as_view(), name='login_driver'),
    path('login/warehouse_worker_driver/', WarehouseWorkerDriverLoginView.as_view(), name='login_warehouse_worker_driver'),

    # Other views
    path('all_employees_list/', AllEmployeesWarehouseListView.as_view(), name='all_employees_warehouse_list'),
    path('warehouse_register/', EmployeeWarehouseRegistrationView.as_view(), name='warehouse_register'),
    path('warehouse_login/', BaseWarehouseLoginView.as_view(), name='warehouse_login'),

]

custom_users/urls.py
from django.urls import path
from custom_users import views
from custom_users.views import ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView

app_name = 'custom_users'  # только если вы используете пространство имен

urlpatterns = [

    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/add/', ClientCreateView.as_view(), name='client_add'),
    path('clients/<int:pk>/edit/', ClientUpdateView.as_view(), name='client_edit'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),

    path('register_clients/', views.register, name='register_clients'),





    path('dashboard_customer/', views.dashboard_customer, name='dashboard_customer'),
    path('profile/update/', views.update_profile, name='update_profile'),
    path('address/add/', views.add_address, name='add_address'),
    path('address/edit/<int:address_id>/', views.edit_address, name='edit_address'),

]

orders/urls.py
from django.urls import path, register_converter

from . import views
from .views import CustomerOrderDetailView, OperatorOrderDetailView, BaseOrderListView, OperatorOrderListView, \
    CanceledOrderListView, DriverOrderDetailView, driver_order_list, mark_notification_as_read
from . import converters
from .views import ProductListView, ProductDetailViewBoxed, ProductDetailViewSingle

register_converter(converters.BoolConverter, 'bool')







app_name = 'orders'  # только если вы используете пространство имен

urlpatterns = [

    path('notifications/read/<int:notification_id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('save-order-details/', views.save_order_details, name='save_order_details'),

    # Путь к странице подтверждения заказа
    path('confirm-order/', views.confirm_order, name='confirm_order'),

    # Пути для обработки результатов платежа через PayPal
    path('payment-success/<uuid:transaction_id>/', views.payment_success, name='payment-success'),
    path('payment-failed/<uuid:transaction_id>/', views.payment_failed, name='payment-failed'),

    # Путь для обработки IPN от PayPal
    path('paypal-ipn/', views.paypal_ipn, name='paypal_ipn'),

    # Путь для подтверждения офлайн-заказа
    path('offline-order-confirm/', views.offline_order_confirm, name='offline_order_confirm'),

    # Путь для страницы деталей заказа (предполагается, что у вас есть такая страница)


    # URL для PayPal IPN
    # path('paypal-ipn/', views.paypal_ipn_listener, name='paypal-ipn'),


    # path('get_client_data/', views.get_client_data, name='get_client_data'),
    path('get-address-details/', views.get_address_details, name='get-address-details'),


    path('order/<int:order_id>/', CustomerOrderDetailView.as_view(), name='customer_order_detail'),
    path('operator/order/<int:order_id>/', OperatorOrderDetailView.as_view(), name='operator_order_detail'),

    path('edit_order_item/<int:order_id>/<str:source>/', views.edit_order_item, name='edit_order_item'),

    path('order_item/delete/<int:order_id>/', views.delete_order_item, name='delete_order_item'),




    path('edit_order_address/<int:order_id>/<str:source>/', views.edit_order_address, name='edit_order_address'),



    path('edit_order_call_add_product/<int:order_id>/<str:source>/', views.EditOrderCallView.as_view(), name='edit_order_call_add_product'),

    path('operator_create_order/', views.operator_create_order, name='operator_create_order'),

    path('order_list/', BaseOrderListView.as_view(), name='base_order_list'),
    path('operator_orders/', OperatorOrderListView.as_view(), name='operator_order_list'),
    path('take_order/<int:order_id>/', views.take_order, name='take_order'),
    path('own_orders/', views.own_operator_order_list, name='own_operator_order_list'),

    path('process_order/<int:order_id>/', views.process_order, name='process_order'),

    path('cancel_order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('canceled_orders/', CanceledOrderListView.as_view(), name='canceled_order_list'),
    path('order/<int:order_id>/return-to-processing/', views.return_order_to_processing_view, name='return_order_to_processing'),

    path('release_order/<int:order_id>/', views.release_order, name='release_order'),
    path('release_order_to_supervisor/<int:order_id>/', views.release_order_to_supervisor, name='release_order_to_supervisor'),

    path('warehouse_orders/', views.warehouse_order_list, name='warehouse_order_list'),
    path('warehouse_orders_d/<int:order_id>/', views.warehouse_order_detail, name='warehouse_order_detail'),
    path('pass_to_warehouse/<int:order_id>/', views.pass_order_to_warehouse, name='pass_order_to_warehouse'),
    path('supervisor_take_order/<int:order_id>/', views.supervisor_take_order_back, name='supervisor_take_order'),

    path('driver_orders/<int:driver_id>/', driver_order_list, name='driver_order'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),

    path('driver_orders/', views.own_driver_order_list, name='own_driver_order_list'),
    path('driver_order_detail/<int:order_id>/', DriverOrderDetailView, name='driver_order_detail'),
    path('pass_to_driver/<int:order_id>/', views.pass_order_to_driver, name='pass_order_to_driver'),
    path('driver_orders/<int:order_id>/mark_as_loaded/', views.mark_as_loaded_driver, name='mark_as_loaded'),
    path('supervisor_mark_as_loaded/<int:order_id>/<int:driver_id>/', views.mark_as_loaded_supervisor,
         name='mark_as_loaded_supervisor'),
    path('mark_truck_as_fully_loaded/', views.mark_truck_as_fully_loaded_driver, name='mark_truck_as_fully_loaded'),
    path('supervisor_mark_truck/<int:driver_id>/', views.mark_truck_as_fully_loaded_supervisor,
         name='mark_truck_as_fully_loaded_supervisor'),
    path('current_user/', views.current_user, name='current_user'),



    path('api/update_based_on_package_call/<str:package_type>/', views.update_based_on_package_call, name='update_based_on_package_call'),
    path('api/update_based_on_product_number_call/<str:package_type>/<str:product_number>/', views.update_based_on_product_number_call,
         name='update_based_on_product_number_call'),
    path('api/update_based_on_sku_call/<str:package_type>/<str:product_number>/<str:size_sku>/', views.update_based_on_sku_call,
         name='update_based_on_sku_call'),

    path('api/update_based_on_size_call/<str:package_type>/<str:product_number>/<str:size_sku>/<str:size_value>/', views.update_based_on_size_call, name='update_based_on_size_call'),



# path('products_order_call/<int:order_id>/add_product/', ProductListView.as_view(), name='product_list_order'),
#     path('product/<slug:slug>/boxed/<int:order_id>/', views.ProductDetailViewBoxed.as_view(),
#          name='product_detail_boxed'),
#     path('product/<slug:slug>/single/<int:order_id>/', views.ProductDetailViewSingle.as_view(), name='product_detail_single'),
#     path('add-product-to-order/<int:product_id>/<int:size_id>/<int:order_id>/', views.add_product_to_order, name='add_product_to_order'),


    path('products_order/<int:order_id>/', ProductListView.as_view(), name='product_list_order'),
    path('products_order/<slug:slug>/boxed/<int:order_id>/', ProductDetailViewBoxed.as_view(),
         name='product_detail_boxed'),

    path('products_order/<slug:slug>/single/<int:order_id>/', ProductDetailViewSingle.as_view(),
         name='product_detail_single'),

    path('add_product/<int:product_id>/<int:size_id>/<int:order_id>/', views.add_product_to_order,
         name='add_product_to_order'),

]

templates/templates_for_office/employee_confirm_delete.html
{% extends "ForMainWepSite/base.html" %}

{% block content %}
  <h2>Confirm Delete</h2>
  <p>Are you sure you want to delete {{ object.user }}?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Yes, Delete</button>
    <a href="{% url 'MainOffice:list_president' %}">Cancel</a>
  </form>
{% endblock %}

templates/templates_for_office/employee_create_update_form.html
{% extends "ForMainWepSite/base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h2>Детализированная информация</h2>
    {{ form.as_p }}
    <input type="submit" value="Сохранить">
</form>



{#  <h2>{% if form.instance.pk %}Update{% else %}Create{% endif %} Employee</h2>#}
{#  <form method="post">#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}#}
{#    <button type="submit">Save</button>#}
{#  </form>#}
{% endblock %}

templates/templates_for_office/employee_list.html
{% extends "ForMainWepSite/base.html" %}

{% block content %}
  <h2>List of Employees</h2>
  <ul>
    {% for employee in object_list %}
      <li>{{ employee.user }}</li>
    {% empty %}
      <li>No employees found.</li>
    {% endfor %}
  </ul>
{% endblock %}

templates/templates_for_office/register.html
{% extends "ForMainWepSite/base.html" %}

{% block content %}
     {% load static %}



	<title>Frog Portal NextJs Template</title>
	<meta charset="UTF-8">
	<meta content="IE=edge" http-equiv="X-UA-Compatible">
	<meta content="width=device-width, initial-scale=1.0" name="viewport">
	<meta content="Generated by create next app" name="description">
	<link href="{% static 'assets/images/froglogo1.svg' %}" rel="icon" sizes="20x20" type="image/gif">
	<meta content="6" name="next-head-count">
	<link href="{% static '/_next/static/css/f43a669c53b6c8f4.css' %}" rel="preload">
	<link data-n-g="" href="{% static '/_next/static/css/f43a669c53b6c8f4.css' %}" rel="stylesheet"><noscript data-n-css=""></noscript>
	<script defer src="{% static '/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js' %}">
	</script>
	<script defer src="{% static '/_next/static/chunks/webpack-c283a3d83359cc25.js' %}">
	</script>
	<script defer src="{% static '/_next/static/chunks/framework-3671d8951bf44e4e.js' %}">
	</script>
	<script defer src="{% static '/_next/static/chunks/main-0905829f35fb5e86.js' %}">
	</script>
	<script defer src="{% static '/_next/static/chunks/3424-510b4663ba497049.js' %}">
	</script>
	<script defer src="{% static '/_next/static/chunks/8004-e80da1eaf59a0e0a.js' %}">
	</script>
	<script defer src="{% static '/_next/static/chunks/7052-5ae32b0979dda73e.js' %}">
	</script>
	<script defer src="{% static '/_next/static/Eiwaci7in8GR_e4MnKVBk/_buildManifest.js' %}">
	</script>
	<script defer src="{% static '/_next/static/Eiwaci7in8GR_e4MnKVBk/_ssgManifest.js' %}">
	</script>
	<link href="{% static '/_next/static/chunks/717-a88701aea31ab923.js' %}" rel="prefetch">
	<link href="{% static '/_next/static/chunks/2008-4f1f586b51905cd8.js' %}" rel="prefetch">
	<link href="{% static '/_next/static/chunks/4875-abff460424e3af31.js' %}" rel="prefetch">
	<link href="{% static '/_next/static/chunks/689-4f6724f50310080b.js' %}" rel="prefetch">
	<link href="{% static '/_next/static/chunks/8863-fb3955eb4b42b806.js' %}" rel="prefetch">
	<link href="{% static '/_next/static/chunks/8960-8ab2b793893d1b59.js' %}" rel="prefetch">
	<link href="{% static '/_next/static/chunks/512-807b1b9847f0c759.js' %}" rel="prefetch">
	<link href="{% static '/_next/static/chunks/4532-630634613f9fb88b.js' %}" rel="prefetch">
	<link href="{% static '/_next/static/chunks/8931-3faabf1b275e128b.js' %}" rel="prefetch">






	<div id="__next">

    <div class="register-area pt-120 mb-120">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="form-wrapper">
                    <div class="form-title">
                        <h3>Register Account</h3><span></span>
                    </div>
                    <div class="register-tab">
                        <nav>
                            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                                <button aria-controls="nav-home" aria-selected="true" class="nav-link active" data-bs-target="#nav-home" data-bs-toggle="tab" id="nav-home-tab" role="tab" type="button" ><a href="{% url 'MainOffice:register_employee' %}">Office</a></button>
                                <button aria-controls="nav-profile" aria-selected="false" class="nav-link" data-bs-target="#nav-profile" data-bs-toggle="tab" id="nav-profile-tab" role="tab" type="button"><a href="{% url 'Warehouse1:warehouse_register' %}">Warehouse</a></button>
                            </div>
                        </nav>
                        <div class="tab-content" id="nav-tabContent">
                            <div aria-labelledby="nav-home-tab" class="tab-pane fade show active" id="nav-home" role="tabpanel">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="row">

                                        <div class="col-md-6">
                                            <div class="form-inner mb-25">
                                                <label for="{{ form.username.id_for_label }}" >Имя пользователя</label>
                                                <div class="input-area">
                                                    <img alt="" src="{% static 'assets/images/icon/user-2.svg' %}" >
                                                    {{ form.username }}

                                                </div>
                                            </div>
                                        </div>


                                        <div class="col-md-6">
                                            <div class="form-inner mb-25">
                                                <label for="{{ form.email.id_for_label }}">Email</label>
                                                <div class="input-area">
                                                    <img alt="" src="{% static 'assets/images/icon/email-2.svg' %}">
                                                    {{ form.email }}
                                                </div>
                                            </div>
                                        </div>


                                        <div class="col-md-6">
                                            <div class="form-inner mb-25">
                                                <label for="{{ form.phone_number.id_for_label }}">Номер телефона</label>
                                                <div class="input-area">
                                                    <img alt="" src="{% static 'assets/images/icon/phone-2.svg' %}">
                                                    {{ form.phone_number }}
                                                </div>
                                            </div>
                                        </div>


                                        <div class="col-md-6">
                                            <div class="form-inner mb-25">
                                                <label for="{{ form.age.id_for_label }}">Возраст</label>
                                                <div class="input-area">
                                                    <img alt="" src="{% static 'assets/images/icon/user-2.svg' %}">
                                                    {{ form.age }}
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-md-6">
                                            <div class="form-inner mb-25">
                                                <label for="{{ form.gender.id_for_label }}">Пол</label>
                                                <div class="input-area">
                                                    <img alt="" src="{% static 'assets/images/icon/user-2.svg' %}">
                                                    {{ form.gender }}
                                                </div>
                                            </div>
                                        </div>

                                         <div class="col-md-6">
                                            <div class="form-inner mb-25">
                                                <label for="role">Выберите роль:</label>
                                                <div class="input-area">
                                                    <img alt="" src="{% static 'assets/images/icon/user-2.svg' %}">
                                                    <select name="role">
                                                        <option value="president">Президент</option>
                                                        <option value="operational_manager">Операционный менеджер</option>
                                                        <option value="accounts_receivable_manager">Менеджер по сбору средств</option>
                                                        <option value="accounts_receivable">Сотрудник по сбору средств</option>
                                                        <option value="accounts_payable">Сотрудник по оплате счетов</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-md-6">
                                            <div class="form-inner mb-25">
                                                <label for="{{ form.password1.id_for_label }}">Пароль</label>
                                                    {{ form.password1 }}
                                                    <i class="bi bi-eye-slash" id="togglePassword"></i>
                                            </div>
                                        </div>

                                        <div class="col-md-6">
                                            <div class="form-inner">
                                                <label for="{{ form.password2.id_for_label }}">Подтверждение пароля</label>
                                                    {{ form.password2 }}
                                                    <i class="bi bi-eye-slash" ></i>
                                            </div>
                                        </div>




                                        <div class="col-md-12">
													<div class="form-agreement form-inner d-flex justify-content-between flex-wrap">
														<div class="form-group two">
															<input id="html1" type="checkbox"><label for="html1">Here, I will agree company terms &amp; conditions.</label>
														</div>
													</div>
												</div>
												<div class="col-md-12">
													<div class="form-inner">
														<button class="primry-btn-2" type="submit">Sign Up</button>
													</div>
												</div>
												<h6>Already have an account?<!-- --> <a href="{% url 'MainOffice:login_employee' %}">Login</a> <!-- -->Here</h6>
												<div class="login-difarent-way">
													<div class="row g-4">
														<div class="col-md-6">
															<a href="https://myaccount.google.com/"><img alt="" src="{% static 'assets/images/icon/google1.svg' %}">Log in with Google</a>
														</div>
														<div class="col-md-6">
															<a href="https://myaccount.google.com/"><img alt="" src="{% static 'assets/images/icon/facebook1.svg' %}">Log in with Facebook</a>
														</div>
													</div>
												</div>

                                    </div>
                                </form>
                            </div>
                            <!-- You can duplicate and adjust the code above for the "Company" tab if needed -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>







	</div>


	<script src="{% static '/_next/static/chunks/717-a88701aea31ab923.js' %}">
	</script>
	<script src="{% static '/_next/static/chunks/689-4f6724f50310080b.js' %}">
	</script>
	<script src="{% static '/_next/static/chunks/2008-4f1f586b51905cd8.js' %}">
	</script>
	<script src="{% static '/_next/static/chunks/4875-abff460424e3af31.js' %}">
	</script>
	<script src="{% static '/_next/static/chunks/8863-fb3955eb4b42b806.js' %}">
	</script>
	<script src="{% static '/_next/static/chunks/8960-8ab2b793893d1b59.js' %}">
	</script>
	<script src="{% static '/_next/static/chunks/512-807b1b9847f0c759.js' %}">
	</script>
	<script src="{% static '/_next/static/chunks/4532-630634613f9fb88b.js' %}">
	</script>
	<script src="{% static '/_next/static/chunks/8931-3faabf1b275e128b.js' %}">
	</script>


{% endblock %}